### ISSUE TITLE
TypeError: 'instancemethod' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by rootlu** [thunlp/OpenNE#1]
In the 27th line of the graph.py, should `self.G.nodes[node]['status'] = ''` be replaced by `self.G.node[node]['status'] = ''` ?

**Comment by zzy14** [comment]
In NetworkX 2.0, `G.node[node]['xxx']` is replaced by `G.nodes[node]['xxx']`. You can update your NetworkX to run our package.

**Comment by rootlu** [comment]
Thanks.
