### ISSUE TITLE
Dead cycle

### ISSUE THREAD

**Issue by gavinjou818** [thunlp/OpenNE#10]
hi,friends. i have a problem that..
1 4
1 5
1 6
1 7
1 9
1 10
1 11
1 12
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
3 7
3 8
3 9
3 10
3 11
3 12
4 7
5 7
6 8
6 11
9 6
7 12
8 12
11 5
10 8

i set these datas on the method “line”,the program will be dead cycle .... Can i solve these problem?

**Comment by zzy14** [comment]
Can you provide some detail like where the dead cycle happened?

**Comment by gavinjou818** [comment]
![_008](https://user-images.githubusercontent.com/17568341/33795456-96459768-dd1c-11e7-8072-8ae49b1a3529.png)

i find the problems on this code..

**Comment by zzy14** [comment]
The input network is too small to find enough negative samples because the default negative_ratio is 5. You can choose a smaller negative_ratio for your input.

**Comment by gavinjou818** [comment]
ok! Thank you i can run this problems when i choose the **batch_size=1** and **negative_ratio=0**
