### ISSUE TITLE
Any one can give me a command line for TADW ?

### ISSUE THREAD

**Issue by myrainbowandsky** [thunlp/OpenNE#103]

**Comment by Bznkxs** [comment]
If you are using OpenNE (old version):
`python -m openne --method tadw --label-file data/cora/cora_labels.txt --input data/cora/cora_edgelist.txt --graph-format edgelist --feature-file data/cora/cora.features --output vec_all.txt`

Or if you are using OpenNE-pytorch (new version):
`python -m openne --model tadw --dataset cora`
