### ISSUE TITLE
How to run GCN on multi-label datasets

### ISSUE THREAD

**Issue by gangwu001** [thunlp/OpenNE#107]
How to run GCN on multi-label datasets, such as blogcatalog and PPI, the codes in gcnModel.py seem only to run the cora dataset. Thanks!

**Comment by Bznkxs** [comment]
Hi Peterecoding,
GCN is a semi-supervised node classification model, so it is supposed to run on attributed graphs, such as cora, pubmed, etc. You can try, though, to adopt it into an unsupervised model (as in [GAE/VGAE](https://github.com/thunlp/OpenNE/blob/pytorch/src/openne/models/gae.py)).

**Comment by gangwu001** [comment]
Fine, thanks for your reply and advice.
