### ISSUE TITLE
Embedding size problem when using SDNE

### ISSUE THREAD

**Issue by droully** [thunlp/OpenNE#108]
When using SDNE, for a graph with n nodes, the resulting embedding is always of size n, independently of the dimension size. Maybe I'm doing something wrong? the command I'm using is:

python -m openne --model sdne --local-dataset --edgefile karate.edgelist --root-dir karate\

 and the resulting embedding file is attached.

[SDNE_embeddings.txt](https://github.com/thunlp/OpenNE/files/5198860/SDNE_embeddings.txt)

Notice that the embedding is 34x34 but the default option is  [1000, 128] so it should be 34x128.

**Comment by Bznkxs** [comment]
Hi @droully, thanks for your question! This is a bug and we have fixed it in the latest commit.
