### ISSUE TITLE
Current requirements allow incompatible versions of libraries to be installed

### ISSUE THREAD

**Issue by apcomello** [thunlp/OpenNE#109]
When I try to install the requirements using the requirements.txt file, per the installation instructions, I end up with incompatible versions of the required libraries. These are the two specific issues I had:

- The numpy version specified (1.14.0) can only be used with tensorflow up to version 1.12.3, but since the requirement for tensorflow only specifies >=1.12.1, an incompatible version can be installed.

- The framework uses something in the tensorflow API that doesn't exist anymore in tensorflow 2, and again due to the specification for tensorflow in the file, an incompatible version can be installed

I've tested the framework with newer versions of numpy, so it seems possible to use the newest version for tensorflow 1 as long as the numpy version is updated accordingly, but at the very least there is a need to specify that you cannot use tensorflow 2 with this.

**Comment by droully** [comment]
i recommend you to use the PyTorch branch: https://github.com/thunlp/OpenNE/tree/pytorch
