### ISSUE TITLE
why do LINE's losses have different forms?

### ISSUE THREAD

**Issue by futureer** [thunlp/OpenNE#11]
While reading/learning the implementation of LINE, I found the first-order loss is different from the LINE paper. 

It involves negative samples which are only used in second-order proximity, and sigmoid function  is not applied to model vertices u_i and u_j (4 lines with sigmoid function are commented). 
 In your code, the loss looks like O_1 = -u_i\*u_j + log(sum(exp(u_i\*u_neg)))

In LINE paper,  except for w_ij are omitted via edge sampling, first-order proximity objective is
![image](https://user-images.githubusercontent.com/3355365/34032808-9c3aa466-e1b2-11e7-894a-3ab626f71c3a.png)

Is there any theoretical or practical explanation to do so?

**Comment by tucunchao** [comment]
Please refer to the explanation in Section 4.2, "For the objective function (3), there exists a trivial solution: uik = ∞, for i=1, . . . , |V | and k = 1, . . . , d. To avoid the trivial solution, we can still utilize the negative sampling approach (7) by just changing ~uj' to ~uj."
