### ISSUE TITLE
The outputs of GCN are not embedding

### ISSUE THREAD

**Issue by imJiawen** [thunlp/OpenNE#110]
Hi there,
Thanks for your hard work.
I want to use the embedding generated by GCN, but its output embedding size is not what I set by "--dim" option.
After checking I found that the dimension of output embedding produced by GCN is the same as the number of labels.

It seems that I cannot set the output embedding size of GCN as I want.
Is it possible to solve this problem? 
Thank you in advance.

**Comment by Qian-Hao** [comment]
I have the same problem!
Have you solved the problem?

**Comment by imJiawen** [comment]
> I have the same problem!
> Have you solved the problem?

Hi @Qian-Hao,
I am afraid that the trained GCN embedding cannot be used directly for other downstream tasks.
Instead, it can only perform node classification task and returns the accuracy of it.
I have used other graph embedding methods as an alternative. :)
