### ISSUE TITLE
Cannot build adjmat from large node list in TADW

### ISSUE THREAD

**Issue by ripingit** [thunlp/OpenNE#112]
I use torch tadw model to train by my dataset ,which have more than 800000 node in graph, when it build adjmat(tadw: line 42) , it throws a memory overflow error like this:
`numpy.core._exceptions.MemoryError: Unable to allocate 5.70 TiB for an array with shape (884901, 884901) and data type float64`

How can i fix it?

Thank you for helping!

**Comment by Bznkxs** [comment]
Hi @ripingit! OpenNE currently needs O(n^2) memory to build an adjacency matrix. We are working on supporting sparse matrix and reducing memory by sampling. You can try using a smaller dataset (eg. a subgraph) for now.
