### ISSUE TITLE
Documentation: relationship between this and KarateClub

### ISSUE THREAD

**Issue by BradKML** [thunlp/OpenNE#113]
It seems that OpenNE does similar algorithm to https://github.com/benedekrozemberczki/karateclub
How is OpenNE different, other than being able to run at a faster pace?

- https://karateclub.readthedocs.io/en/latest/notes/resources.html#neighbourhood-based-node-embedding
- https://karateclub.readthedocs.io/en/latest/notes/resources.html#structural-node-embedding

**Comment by BradKML** [comment]
Also algo list https://github.com/zhilonglu/Network-Embedding
for evaluation https://github.com/Dru-Mara/EvalNE

**Comment by Bznkxs** [comment]
Hi @BrandonKMLee! Thanks for your question. OpenNE implements several standard network embedding algorithms, and so they will be similar to other tool kits that implement the same algorithms. OpenNE mainly differs in its architecture that provides a unified framework.

**Comment by BradKML** [comment]
I wonder if this framework will include the other algorithms used in KarateClub

**Comment by Bznkxs** [comment]
We currently do not have plans to include other algorithms, but any pull request will be welcome.
