### ISSUE TITLE
Error module 'tensorflow' has no attribute 'app'

### ISSUE THREAD

**Issue by Milad-Hosseini** [thunlp/OpenNE#115]
After i install the requirement.txt file, I face such an error. I think this **TensorFlow compatibility**.
you can change **"import tensorflow as tf"** to **"import tensorflow.compat.v1 as tf"**
it worked for me.
[see this](https://stackoverflow.com/questions/58258003/attributeerror-module-tensorflow-has-no-attribute-app)

**Comment by Bznkxs** [comment]
Hi @Milad-Hosseini! Thanks for your suggestion. Since the TensorFlow version has not been maintained for a while, errors like this could happen. We will fix this nevertheless.
