### ISSUE TITLE
running on GPU

### ISSUE THREAD

**Issue by island255** [thunlp/OpenNE#116]
Hi, I have a question about running OpenNE on GPU. 

I have created a docker with TensorFlow-gpu and can successfully use GPU to run simple codes, but failed to run TADW using GPU.

Is there a way to run this TensorFlow version on GPU or we can only run the PyTorch version on GPU?

**Comment by island255** [comment]
It seems that TADW in the PyTorch version is also not implemented to run on GPU.  Will it support it in the future?

**Comment by Bznkxs** [comment]
Hi @island255 ! Thanks for your suggestion. We have added GPU support for TADW in the latest commit.
