### ISSUE TITLE
type error on my local dataset "TypeError: __init__() got an unexpected keyword argument 'silent'"

### ISSUE THREAD

**Issue by ZipECHO** [thunlp/OpenNE#117]
hi, I am runing deepwalk model on my dataset, my dataset is an weighted and directed edgelist. without label file. I run following command:
`python -m openne --model deepwalk --local-dataset --root-dir ../penpa/city_graph/data/edgelist/move_in/ --edgefile 2020-01-10-edgelist.txt --weighted --directed --name citygraph`
but I got : TypeError: __init__() got an unexpected keyword argument 'silent'.
For what you have provided dataset, there will be ok.

here is the detail feedback:
`Traceback (most recent call last):
  File "/data/GAOZip/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/GAOZip/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/GAOZip/OpenNE-pytorch/src/openne/__main__.py", line 240, in <module>
    main(parse_args())
  File "/data/GAOZip/OpenNE-pytorch/src/openne/__main__.py", line 227, in main
    graph = Graph(silent=train_args['silent'])  # prepare dataset
TypeError: __init__() got an unexpected keyword argument 'silent'`

waiting for your replay : )
thanks

**Comment by night-changes** [comment]
> hi, I am runing deepwalk model on my dataset, my dataset is an weighted and directed edgelist. without label file. I run following command: but I got : TypeError: **init**() got an unexpected keyword argument 'silent'. For what you have provided dataset, there will be ok.`python -m openne --model deepwalk --local-dataset --root-dir ../penpa/city_graph/data/edgelist/move_in/ --edgefile 2020-01-10-edgelist.txt --weighted --directed --name citygraph`
> 
> here is the detail feedback: `Traceback (most recent call last): File "/data/GAOZip/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/data/GAOZip/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/data/GAOZip/OpenNE-pytorch/src/openne/__main__.py", line 240, in <module> main(parse_args()) File "/data/GAOZip/OpenNE-pytorch/src/openne/__main__.py", line 227, in main graph = Graph(silent=train_args['silent']) # prepare dataset TypeError: __init__() got an unexpected keyword argument 'silent'`
> 
> waiting for your replay : ) thanks

Hello, the result of my operation is the same as yours. How to solve this problem？thanks.

**Comment by Bznkxs** [comment]
Hi @ZipGao and @Zhuandong0721 ,

Sorry for the inconvenience. This bug occurs because class `SelfDefined` which is defined in `create_self_defined_dataset` from `dataloaders/graph.py` does not accept `silence` as parameter. The bug is now fixed. Thanks for bringing up this issue!
