### ISSUE TITLE
能改成python3的代码吗，win10系统装不了python2的tensorflow

### ISSUE THREAD

**Issue by xiexiaomiao** [thunlp/OpenNE#12]

**Comment by futureer** [comment]
There are not many complex compatible issues, you can simply replace 'print xx' and 'xrange' with 'print(xx)' and 'range' in the code and run in py3.

**Comment by benelot** [comment]
I am just working on fixing this issue by making the library python2/python3 compatible. For now it seems that the main thing is just print. Anything else I should look for? For now it seems that it runs well.
