### ISSUE TITLE
TypeError: 'method' object is not subscriptable

### ISSUE THREAD

**Issue by yagami0939** [thunlp/OpenNE#26]
Hello, I ran an example with following command, but I got an error.
My python version is Python 3.6.0 :: Anaconda custom (64-bit)

Here is the detail.

command:
> python src/main.py --method gcn --label-file data/cora/cora_labels.txt --input data/cora/cora_edgelist.txt --graph-format edgelist --feature-file data/cora/cora.features  --epochs 200 --output vec_all.txt --clf-ratio 0.1

error:

> Using TensorFlow backend.
> Reading...
> Traceback (most recent call last):
>   File "src/main.py", line 125, in <module>
>     main(parse_args())
>   File "src/main.py", line 77, in main
>     g.read_edgelist(filename=args.input, weighted=args.weighted, directed=args.directed)
>   File "/home/lzc/p/OpenNE/src/libnrl/graph.py", line 76, in read_edgelist
>     self.encode_node()
>   File "/home/lzc/p/OpenNE/src/libnrl/graph.py", line 27, in encode_node
>     self.G.nodes[node]['status'] = ''
> TypeError: 'method' object is not subscriptable

**Comment by zzy14** [comment]
Hi, I guess you have the same problem in https://github.com/thunlp/OpenNE/issues/9.
