### ISSUE TITLE
Can Node2vec use the label of Nodes ?

### ISSUE THREAD

**Issue by zhouchunpong** [thunlp/OpenNE#29]
python src/main.py --method node2vec --label-file data/blogCatalog/bc_labels.txt

**Comment by zzy14** [comment]
Node2vec doesn't use the label while training. You can read its [paper](http://www.kdd.org/kdd2016/papers/files/rfp0218-groverA.pdf) for details.

**Comment by zhouchunpong** [comment]
thank you for your answers!
I just think this usage example may cause misleading.
-- Best wishes
