### ISSUE TITLE
Convert index of node to int while reading nodel labels

### ISSUE THREAD

**Issue by Songweiping** [thunlp/OpenNE#3]
Hi,
In this line: https://github.com/thunlp/OpenNE/blob/ed2e4dcf1f3237fd33f72259c1d680a183de6f5a/src/libnrl/classify.py#L94, perhaps you should convert `vec[0]` to int. Otherwise, it will cause TypeError when using x as an index.

**Comment by zzy14** [comment]
`vec[0]` is the name of node. It will use nodes' name to look up their embeddings(using a dictionary). So int and str are both suitable here.

**Comment by Songweiping** [comment]
Yeah, thanks for your reply. I misunderstood the variable `self.vectors` as a list.
