### ISSUE TITLE
Example problem

### ISSUE THREAD

**Issue by rGitcy** [thunlp/OpenNE#32]
MY install is ok,but when i process the example,, it maintain in the status:
(openNE_env) ruancy@dell-SYS-7048GR-TR:~/OpenNE-master$     python src/main.py --method node2vec --label-file data/blogCatalog/bc_labels.txt --input data/blogCatalog/bc_adjlist.txt --graph-format adjlist --output vec_all.txt --q 0.25 --p 0.25
 Reading...
Preprocess transition probs...

**Comment by zzy14** [comment]
Hi, it should take some time to preprocess since BlogCatalog dataset has amounts of edges.
