### ISSUE TITLE
Does the code support running in parallel in the sampling stage?

### ISSUE THREAD

**Issue by zhushun0008** [thunlp/OpenNE#33]
Does the code support running in parallel in the sampling stage?

**Comment by zzy14** [comment]
No. We just wrote a single-thread code for sampling. You can help us extend it.

**Comment by Bznkxs** [comment]
Hi zhushun0008,
We will consider supporting parallel sampling in our new [PyTorch version](https://github.com/thunlp/OpenNE/tree/pytorch).
