### ISSUE TITLE
GCN output problem

### ISSUE THREAD

**Issue by caijiangyao1991** [thunlp/OpenNE#34]
i cant't find the output vec_all.txt when running GCN, 
python src/main.py --method gcn --label-file data/cora/cora_labels.txt --input data/cora/cora_edgelist.txt --graph-format edgelist --feature-file data/cora/cora.features  --epochs 200 --output vec_all.txt --clf-ratio 0.1

the precedure didnot have the model save or embedding save or how to predict the new data

**Comment by zzy14** [comment]
In this package, the output file is for saving the node embeddings. Since GCN just has the convolution kernels, the output parameter is useless for GCN. I have updated README to clarify that.

**Comment by Tomposon** [comment]
But how can I get the node embedding with the GCN? @zzy14

**Comment by Tomposon** [comment]
Have you solved this problem:get the embeddings? @caijiangyao1991

**Comment by caijiangyao1991** [comment]
@Tomposon  i don't get the embeddings , i just get the prediction of  new data

**Comment by Tomposon** [comment]
Do you mean that your task is to do the node classification?But I want to get the node embedding with the GCN.I think the GCN implemented here is an end-to-end algorithm,am I right?

**Comment by caijiangyao1991** [comment]
@Tomposon yes you are right

**Comment by Tomposon** [comment]
Thank you! @caijiangyao1991

**Comment by gopick** [comment]
@zzy14 can you elaborate on why the output parameter is useless for GCN? How do we change this code to obtain the node embeddings from the GCN model?

**Comment by gopick** [comment]
@Tomposon  @caijiangyao1991  Have you guys figured out a way to obtain the node embeddings from GCN?

**Comment by Tomposon** [comment]
No,I choose another algorithm GraphSAGE.

**Comment by Tomposon** [comment]
No,I choose another algorithm GraphSAGE. @gopick

**Comment by CynthiaWang2018** [comment]
@Tomposon Have you obtain the node embeddings with GraphSage?

**Comment by Tomposon** [comment]
@CynthiaWang2018 You can use the unsupervised version, you could see the information about embeddings saving in the source code.

**Comment by CynthiaWang2018** [comment]
@Tomposon I have transform the original social network dataset into an ' .edgelist'  document. (No feature ,No labels)Can I use the GraphSAGE algrithm or some other GCN methods get the representation of all nodes?

**Comment by beyondguo** [comment]
> 
> 
> In this package, the output file is for saving the node embeddings. Since GCN just has the convolution kernels, the output parameter is useless for GCN. I have updated README to clarify that.

Why are you saying the output parameters of GCN are useless? The effective graph embedding is also one of the contributions of GCN.

**Comment by beyondguo** [comment]
> 
> 
> No,I choose another algorithm GraphSAGE. @gopick

Hi, are you using the code from GraphSage's official github https://github.com/williamleif/GraphSAGE to get the node embedding? Thank you!

**Comment by Bznkxs** [comment]
Hi,
Thanks for your discussion. Our new OpenNE-PyTorch update (https://github.com/thunlp/OpenNE/tree/pytorch) has solved this and you can find output in results/GCN after running
```
python -m openne --model gcn --dataset cora
```
