### ISSUE TITLE
did you compared you performance with MNE: Scalable Multiplex Network Embedding

### ISSUE THREAD

**Issue by Sandy4321** [thunlp/OpenNE#35]
did you compared you performance with MNE
#http://www.cse.ust.hk/~yqsong/papers/2018-IJCAI-MultiplexNetworkEmbedding.pdf
#https://github.com/HKUST-KnowComp/MNE

**Comment by jayzzhou-thu** [comment]
Hi @Sandy4321, we test the methods only on homogeneous networks. MNE is a method designed for multiplex networks and the datasets are multiplex networks. You can try our methods on these datasets if you are interested.

**Comment by Sandy4321** [comment]
homogeneous networks
What is it?

**Comment by jayzzhou-thu** [comment]
> homogeneous networks
> What is it?

Hi @Sandy4321, here is an introduction to homogeneous networks and heterogeneous networks. 
https://guides.co/g/the-network-effects-bible/121732
