### ISSUE TITLE
can it be used in Windows computer?

### ISSUE THREAD

**Issue by Sandy4321** [thunlp/OpenNE#36]
can it be used in Windows computer?

**Comment by zzy14** [comment]
Yes, of course.

**Comment by Sandy4321** [comment]
super
thanks
installation was ok 
but what example can be used?
I try to run main file 
I have this error
File "e:\AAA_new_Lenovo_start_sep_22_2018\Graphs_ML\code\OpenNE-master\OpenNE-master\src\openne\__main__.py", line 6, in <module>
  from .graph import *

builtins.ImportError: attempted relative import with no known parent package
