### ISSUE TITLE
We should cite which paper when we  get f-score used your code ?

### ISSUE THREAD

**Issue by gangwu001** [thunlp/OpenNE#44]

**Comment by cwchenwang** [comment]
i think no paper needed

**Comment by tucunchao** [comment]
You can cite this one:
@Article{tu2017network,
  Title                    = {Network representation learning: an overview},
  Author                   = {TU, Cunchao and YANG, Cheng and LIU, Zhiyuan and SUN, Maosong},
  Journal                  = {SCIENTIA SINICA Informationis},
  Volume                   = {47},
  Number                   = {8},
  Pages                    = {980--996},
  Year                     = {2017}
}
