### ISSUE TITLE
TADW - dimension goof-up

### ISSUE THREAD

**Issue by anirban-code-to-live** [thunlp/OpenNE#46]
I tried to generate an embedding of size 128. I put the dimension accordingly, but the embeddings generated were of size 256. Then I tried with keeping dimension parameter 64, surprisingly the outout generated having dimension 128.

It was working fine for dimension 32.

**Comment by zzy14** [comment]
The code does double the dimension of TADW. This bug has been fixed. 

Thank you for your issue.
