### ISSUE TITLE
some problem about installing

### ISSUE THREAD

**Issue by jerrywu65** [thunlp/OpenNE#49]
I cloned it to my server(Ubuntu 16.04.4 LTS).Here is the path “/home/ruancy/wrj/OpenNE-master/”
I input “python setup.py install” to install.Then I input "python -m openne --help"
I get an error,Here it is:
Traceback (most recent call last):
  File "/home/ruancy/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ruancy/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ruancy/anaconda3/lib/python3.6/site-packages/openne-0.0.0-py3.6.egg/openne/__main__.py", line 7, in <module>
    import node2vec
ModuleNotFoundError: No module named 'node2vec'

**Comment by zzy14** [comment]
Hi, I have updated the code. You can try it again. Let me know if you have any questions.

**Comment by jerrywu65** [comment]
> Hi, I have updated the code. You can try it again. Let me know if you have any questions.
Thank you ! now I can run the example successfully.Could you tell me how to run .edgelist file,such as data/karate/karate.edgelist?

**Comment by zzy14** [comment]
> > Hi, I have updated the code. You can try it again. Let me know if you have any questions.
> > Thank you ! now I can run the example successfully.Could you tell me how to run .edgelist file,such as data/karate/karate.edgelist?

Use these args: --graph-format edgelist --input data/karate/karate.edgelist
