### ISSUE TITLE
Error when running example of LINE

### ISSUE THREAD

**Issue by OswinGuai** [thunlp/OpenNE#5]
When run the following cmd,
`python src/main.py --method line --label-file data/blogCatalog/bc_labels.txt --input data/blogCatalog/bc_adjlist.txt --graph-format adjlist --output vec_all.txt`
And get error,

> File "/home/***/runspace/OpenNE/src/libnrl/graph.py", line 27, in encode_node
    self.G.nodes[node]['status'] = ''
TypeError: 'instancemethod' object has no attribute '__getitem__'

**Comment by zzy14** [comment]
Maybe your Networkx version is not correct. You can see this issue #1 .
