### ISSUE TITLE
minor suggestion on your implementation of line.py

### ISSUE THREAD

**Issue by EtoDemerzel0427** [thunlp/OpenNE#53]
When we apply both 1st and 2nd LINE,  the sampling table of nodes and the alias table of edges will be constructed twice, since you put the constructing step in the class `_LINE` and this class is called twice.  And I think moving it to the class `LINE` can solve this and it would not be difficult, so why not?

**Comment by zzy14** [comment]
Sounds great. We welcome a new pull request about it.

**Comment by EtoDemerzel0427** [comment]
> Sounds great. We welcome a new pull request about it.

Also, it seems we are not allow to change the number of batch size without modifying the source code; you simply did not provide such argument. 

btw in the README.md, you say the default number of epochs in LINE and GCN is 5; while I notice in LINE, it's 10 and in GCN it should be 200.

**Comment by jayzzhou-thu** [comment]
Good idea. I think we can implement it in our Pytorch version.
