### ISSUE TITLE
questions about multiprocess in walker.py

### ISSUE THREAD

**Issue by KenGeng** [thunlp/OpenNE#54]
In your walker.py, I find that you comment out multiprocessing part. I'd like to run random walk process for many times. So, I am wondering whether it is ok for me to just cancel the comment and run the code on a server.
Looking forward to your reply~

**Comment by sun-xiaoyu** [comment]
Same issue. It seems the parameter "workers" is not working. Do you have a fix on that ?

**Comment by Bznkxs** [comment]
The multiprocessing part is cancelled because there would be too many processes ( =num_walks * node_size) which would take up most of the resources just switching between processes. We are currently looking for a better way to implement multi-processing.
