### ISSUE TITLE
A bug for LINE

### ISSUE THREAD

**Issue by KenGeng** [thunlp/OpenNE#56]
I find in the _main.py, users can pass the parameter 'negative-ratio' into openne, however, when _main.py calls line.py, it does not pass such parameter into the line.py.
Looking forward to your reply and fix

**Comment by Bznkxs** [comment]
Hi KenGeng,
Thanks for your issue. We've fixed this in our new OpenNE-PyTorch version (https://github.com/thunlp/OpenNE/tree/pytorch).
