### ISSUE TITLE
Problems with respect to different ratio of training images in GCN.

### ISSUE THREAD

**Issue by d12306** [thunlp/OpenNE#59]
Hello, there, first thank for making the code available online, but I have a few questions about testing the GCN model using the cora dataset. If I change the ---clf-ratio to 0.01, the training and evaluation loss is nan. How can that happen, hopefully I can get your attention, thanks,

**Comment by Bznkxs** [comment]
Hi d12306!
Since there are only 2,708 nodes in Cora, wouldn't it be a little bit too small for clf-ratio==0.01? I suggest using a bigger clf-ratio, for example 0.1, or a bigger dataset, which we provide in our new PyTorch version (https://github.com/thunlp/OpenNE/tree/pytorch).
