### ISSUE TITLE
Why not use the Classifier(LogisticRegression) to evaluate the performance of GCN?

### ISSUE THREAD

**Issue by BenchengY** [thunlp/OpenNE#60]
It seems that the acc of GCN is directly obtained from the GCN net, while the acc of other methods are obtained from the Classifier(LogisticRegression).
Is it fair to compare the performance between GCN and others by different classifiers (i.e., GCN net and LogisticRegression)?
Why not use the Classifier(LogisticRegression) to evaluate the performance of GCN?

**Comment by zzy14** [comment]
GCN is a semi-supervised method while other methods are unsupervised network embedding methods. GCN can directly predict the labels of nodes.

**Comment by BenchengY** [comment]
Although GCN can directly predict the labels of nodes， is it fair to compare the performance between GCN and others by different classifiers (i.e., GCN net and LogisticRegression)?

**Comment by Bznkxs** [comment]
Hi BenchengY,
GCN is used in semi-supervised node classification, which is a different task from unsupervised node classification (with methods such as Node2vec and GraRep). There is no way to compare these two tasks. I think it is also unfair to put GCN embeddings into a classifier and compare with other methods by classifiers.
