### ISSUE TITLE
Problem with LLE

### ISSUE THREAD

**Issue by senjed** [thunlp/OpenNE#65]
The generated embedding contains Nans whenever the matrix rank is lower than dim + 1.

**Comment by Bznkxs** [comment]
Hi senjed,
LLE is a method for Euclidean space embedding which involves building a graph (see [Nonlinear Dimensionality Reduction by Locally Linear Embedding](http://www.robots.ox.ac.uk/~az/lectures/ml/lle.pdf)), so it may not be so suitable for network embedding. Maybe you should try on more recent methods like Node2vec, GraRep and TADW.
