### ISSUE TITLE
请问LINE得到的嵌入可以直接用作论文的对比结果吗

### ISSUE THREAD

**Issue by prejefferson** [thunlp/OpenNE#67]
我在一个数据集Ca-GrQc上使用了OpenNE中的LINE算法，并且通过得到的嵌入向量计算了AUC值，请问AUC的结果可以作为LINE的结果来和我的实验结果做对比吗？
因为我发现训练集的比例越大，在LINE的AUC值越低，不知道是不是可以作为参考的基线算法，如果不行的话，能告诉我怎么做吗，谢谢！！

**Comment by FanGhost** [comment]
论文的话建议还是跑LINE作者开源的那个算法吧 保险一点

**Comment by jayzzhou-thu** [comment]
hi @prejefferson, 如果是新的数据集的话，建议您将LINE作为baseline时使其与其他方法保持一样的实验设定，并尽可能多地进行一些调参，这样能够确保实验结果的准确性与公平性。保险一点的话也可以使用LINE的源代码。
