### ISSUE TITLE
BlogCatalog数据集SDNE算法的参数设置？

### ISSUE THREAD

**Issue by imaomao** [thunlp/OpenNE#68]
我尝试了一些参数设置，micro-F1只能达到36%，想问一下SDNE在BlogCatalog数据集上的参数应该怎么设置？

**Comment by Freyr-Wings** [comment]
你好，当时时间比较紧，只测了wiki数据集的，也许你可以试试带衰减的学习率，或者试试SDNE2（使用前建议先看看源码）。

**Comment by Diamond0728** [comment]
朋友，可以请教一下结果达到36%的参数设置是什么吗？ @imaomao

**Comment by Bznkxs** [comment]
您好，我们又找了几份源代码也还是无法达到论文的效果。可以去联系一下原作者。
