### ISSUE TITLE
hope

### ISSUE THREAD

**Issue by timeflow-lab** [thunlp/OpenNE#69]
您好，在hope算法里读取边列表虽然进行了encode_node，但并没有使用look_up_dict，为什么在vectors的定义里却使用了look_back_list

**Comment by Bznkxs** [comment]
您好，look_up_dict和look_back_list是在将数据读入networkx时维护的原始结点编号和networkx中结点编号的映射关系，分别对应正向映射和逆向映射。由于从networkx得到的邻接矩阵的编号正是networkx中的结点编号而不是原编号，所以不需要look_up_dict。但是当保存到vectors时，需要从networkx结点编号转回原编号，所以需要look_back_list。
