### ISSUE TITLE
the use of GCN

### ISSUE THREAD

**Issue by wanghonen** [thunlp/OpenNE#70]
hello,i just ran GCN on the command line ,but it just gives me some result text,i don not konw how to use the GCN, eyeryone  who can help me ?

**Comment by Bznkxs** [comment]
Hi wanghonen!

In OpenNE, GCN is trained to predict node labels. 
You can look at the last two lines, which give you something like this:

> Test set results: cost= 0.97424 accuracy= 0.81583 time= 0.03395
> 16.793111324310303

The first line shows GCN performance on the dataset you appointed. You should especially look into "accuracy", which means "the accurate label predictions" divided by "all predictions". 

The second line shows the overall training and testing time, in second.
