### ISSUE TITLE
Can you make this repository as a python package

### ISSUE THREAD

**Issue by lingling93** [thunlp/OpenNE#72]
Hi guys:
You are doing really good job. But with such a repository, it's not very user-friendly. If you make this a python package could be used as 'pip install packagename', then everything works. That would be much better for reproducibility.
Regards
LIngling

**Comment by huber-yaoer** [comment]
I also feel unfriendly. I feel that developers focus on presentation, not sharing.

**Comment by jayzzhou-thu** [comment]
Hi, thanks for your suggestion! We plan to build a python package for our Pytorch version.
