### ISSUE TITLE
Can I extract probabilities of co-occurences of node2vec

### ISSUE THREAD

**Issue by LPioL** [thunlp/OpenNE#74]
Hello,

Is it possible using node2vec to extract the matrix of probability co-occurence ?

Thanks.

**Comment by Bznkxs** [comment]
Hello LPioL,
node2vec is implemented by wrapping word2vec, which [just iterates over the entire training corpus in multiple passes, never creating a co-occurrence matrix](https://stackoverflow.com/questions/52391572/gensim-how-to-extract-words-co-occurrence). You can extract co-occurrence by using the **sentence** created in random walk. Check out co-occurrence in the link above.

**Comment by myrainbowandsky** [comment]
they are totally the different thing.
