### ISSUE TITLE
Node2vec Library speed 

### ISSUE THREAD

**Issue by ZhiyuanCao98** [thunlp/OpenNE#76]
I saw the result of the elapsed time of openNE(node2vec) are slower than the regular library. 1. Could you describe the result of why it will happen? 
2. Can node2vec support multi-gpu 

> run?

**Comment by ZhiyuanCao98** [comment]
I saw the source code, you just directly use the Node2vec library, so it does not support multi-gpu yet

**Comment by tryggviy** [comment]
I also find that in source codes. The title of this project makes me believe that they have supported node2vec with GPU. They may support it soon.

**Comment by Bznkxs** [comment]
Hi,
Thanks for your discussion! We now support GPU in our new version (https://github.com/thunlp/OpenNE/tree/pytorch) and are currently working on multi-GPU. Please stay tuned!
