### ISSUE TITLE
python包

### ISSUE THREAD

**Issue by DreamerDW** [thunlp/OpenNE#77]
可以再确认一下Python版本以及包的版本吗，安装一直出错，谢谢

**Comment by way2geek** [comment]
python3.6  tensorflow 1.14.1  cuda10  cudnn7.5
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: DreamerDW <notifications@github.com>
发送时间: 2019年7月2日 14:55
收件人: thunlp/OpenNE <OpenNE@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[thunlp/OpenNE] python包 (#77)




可以再确认一下Python版本以及包的版本吗，安装一直出错，谢谢

**Comment by jayzzhou-thu** [comment]
@DreamerDW  您好，我们推荐使用python 3.6，tensorflow的版本应大于1.12.1。
