### ISSUE TITLE
Has the NEU algorithm been implemented now?

### ISSUE THREAD

**Issue by eecrazy** [thunlp/OpenNE#8]
NEU in this paper: Fast Network Embedding Enhancement via High Order Proximity Approximation

**Comment by eecrazy** [comment]
As the NEU algorithm is so useful according to the experimental results, I suggest adding it as an extra option.

**Comment by zzy14** [comment]
Good idea! We will add it in the future. Now you can use [NEU implemented by Matlab](https://github.com/thunlp/NEU) to enhance your NRL.
