### ISSUE TITLE
Installation on kaggle or colab succeed but module is not found

### ISSUE THREAD

**Issue by mosheliv** [thunlp/OpenNE#82]
I think it has something to do with conda environment.

see https://www.kaggle.com/moshel/openne-test or https://colab.research.google.com/drive/1_NJ9nZ13ha_qwWKWIozq_ICu377uak11

**Comment by Bznkxs** [comment]
See [this](https://stackoverflow.com/questions/52483662/unable-to-import-module-in-google-colab-after-installing) for colab installation.

Kaggle installation failure may have something to do with the max nested directory limit (6).
