### ISSUE TITLE
tadw.py-87行：对H求偏导得到的式子的第一个加法项是不是少了个系数2

### ISSUE THREAD

**Issue by RealTommyHu** [thunlp/OpenNE#83]
<img width="529" alt="`~)} }{9L0(4(7EH(TJ(JLB" src="https://user-images.githubusercontent.com/19240852/64059869-e1ab3d00-cbf6-11e9-94e2-efb0beac02d5.png">

**Comment by JianglongHu** [comment]
<img width="529" alt="`~)} }{9L0(4(7EH(TJ(JLB" src="https://user-images.githubusercontent.com/19240852/64059864-cb9d7c80-cbf6-11e9-855d-e6bb42d51cbb.png">

**Comment by Bznkxs** [comment]
您好，的确是这样。我们将会在新版（https://github.com/thunlp/OpenNE/tree/pytorch）中改正过来。
