### ISSUE TITLE
Cora dataset

### ISSUE THREAD

**Issue by hoangdzung** [thunlp/OpenNE#84]
How do you get the Cora dataset? I compare the one you provide with this [one](https://github.com/tkipf/pygcn/tree/master/data/cora). Two graphs are isomorphic but the labels are different.
Thank you.

**Comment by cgq15** [comment]
We download Cora, Citeseer and Pubmed from [Planetoid datasets](https://github.com/kimiyoung/planetoid/raw/master/data).
