### ISSUE TITLE
Cannot install on OS X

### ISSUE THREAD

**Issue by sming** [thunlp/OpenNE#89]
Hi,

I'm trying to install on OS X 10.14.6 and the `numpy` build fails with:
```  _configtest.c:1:10: fatal error: 'endian.h' file not found```

I found [this SO answer](https://stackoverflow.com/a/52904079/1170932) and followed the instructions to no avail. 

Then I tried commenting out `numpy` from `requirements.txt` but then `scipy` failed to build.

Any help would be appreciated,
Pete

**Comment by sming** [comment]
Actually I got ```python -m openne --help``` working by creating an `environment.yml` file with the packages from `requirements.txt`. I'll see if this actually runs.

**Comment by sming** [comment]
OK, the sample command:
```python -m src.openne --method node2vec --label-file data/blogCatalog/bc_labels.txt --input data/blogCatalog/bc_adjlist.txt --graph-format adjlist --output vec_all.txt --q 0.25 --p 0.25```
is running successfully. 

Let me know if you want me to raise a PR to add the `environment.yml`.

**Comment by Bznkxs** [comment]
Hi sming!
Thanks for your question and you are always welcome to raise a PR.
