### ISSUE TITLE
A TypeError When I run example

### ISSUE THREAD

**Issue by maxiaozte** [thunlp/OpenNE#9]
I meet an error as below when I run example: 
"""
File "src\libnrl\graph.py", line 27, in encode_node 
self.G.nodes[node]['status'] = ''  
TypeError: 'method' object is not subscriptable
"""
I use python3.

**Comment by zzy14** [comment]
Maybe the version of NetworkX is not correct. In NetworkX 2.0, we can handle G.nodes in this way. You can see [the tutorial of NetworkX 2.0](https://networkx.github.io/documentation/stable/tutorial.html).

**Comment by maxiaozte** [comment]
It's helpful. Thanks.

**Comment by mattivi** [comment]
I get the same error, but I have networkx v2.2. 
Any hint?

**Comment by xiaotianyu666** [comment]
It help thanks
