### ISSUE TITLE
Tensorflow version problem

### ISSUE THREAD

**Issue by Diamond0728** [thunlp/OpenNE#91]
Nowdays, tensorflow 2.0 has been published, it is not compatible with tensorflow 1.x。And due to the code in requirements.txt:
```
tensorflow >= 1.12.1
```

pip will install tensorflow 2.0 instead of 1.x, which will cause the pip install error

**Comment by Rat-racer** [comment]
yes, the code is only compatible with tesorflow1.X。
if you're tensorflow2.0 ,runing the code will cause error(eg. gcn methods ) , because tf2.0 is not compatible with tensorflow 1.X .So requirements.txt should be written as tensorflow = 1.12.1
