### ISSUE TITLE
GCN running problem

### ISSUE THREAD

**Issue by raniasaidi** [thunlp/OpenNE#92]
Hello everyone !
When i run the command : 
`python -m openne --method gcn --label-file data/cora/cora_labels.txt --input data/cora/cora_edgelist.txt --graph-format edgelist --feature-file data/cora/cora.features  --epochs 200 --output vec_all.txt --clf-ratio 0.1`
I get this error: 
```

File "/home/enx/Downloads/OpenNE-master/OpenNE-env2/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 64, in getter
    return captured_getter(captured_previous, **kwargs)
TypeError: 'str' object is not callable

```

**Comment by Rr-shan** [comment]
change the name of str

**Comment by Bznkxs** [comment]
Hi raniasaidi,
Thanks for your question. I didn't run into this error with Python 3.7 and TensorFlow 1.15.0. Maybe you should check your environment.
