### ISSUE TITLE
有权图的数据集/例子有吗

### ISSUE THREAD

**Issue by SeekPoint** [thunlp/OpenNE#95]

**Comment by Bznkxs** [comment]
您好，我们目前尚未提供有权图的数据集。OpenNE是以无权图格式读取数据的，您可以尝试修改代码读取有权图。

**Comment by yangguangbegin0000** [comment]
请问能提供PPI数据集吗？

**Comment by Bznkxs** [comment]
@yangguangbegin0000 您好，
我们的新版本OpenNE-PyTorch提供了PPI数据集，请访问https://github.com/thunlp/OpenNE/tree/pytorch
